# Generated by Django 4.2.3 on 2023-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_latlngcity_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageText', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='latlngcity',
            name='Zone',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue')], default='Green', max_length=20),
        ),
    ]
