# Generated by Django 4.2.3 on 2023-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0011_newimagemodel_alter_latlngcity_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewUserModel",
            fields=[
                (
                    "UserName",
                    models.CharField(
                        default="", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("Password", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
