# Generated by Django 4.2.3 on 2023-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0012_newusermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="newimagemodel",
            name="entrytime",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="newimagemodel",
            name="username",
            field=models.CharField(default="", max_length=20),
        ),
    ]
